[package]
authors = [ "Jan-Hendrik Matthes" ]
autoexamples = false
categories = [ "parser-implementations", "parsing", "text-editors" ]
description = "Curry grammar for tree-sitter"
edition = "2024"
keywords = [ "incremental", "parsing", "tree-sitter", "curry" ]
license = "MIT"
name = "tree-sitter-curry"
readme = "README.md"
repository = "https://github.com/matthesjh/tree-sitter-curry.git"
version = "0.0.4"

build = "bindings/rust/build.rs"
include = [ "bindings/rust/*", "grammar.js", "queries/*", "src/*", "tree-sitter.json", "/LICENSE" ]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.27.0"
