import js from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'
import { defineConfig } from 'eslint/config'

export default defineConfig([
  {
    files: ['**/*.js', '**/*.ts'],
    ignores: ['bindings/**'],
    plugins: {
      js,
    },
    extends: [
      'js/recommended',
      stylistic.configs.customize({
        arrowParens: false,
        blockSpacing: true,
        braceStyle: 'stroustrup',
        commaDangle: 'always-multiline',
        indent: 2,
        jsx: true,
        quoteProps: 'as-needed',
        quotes: 'single',
        semi: false,
      }),
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        alias: 'readonly',
        choice: 'readonly',
        field: 'readonly',
        grammar: 'readonly',
        optional: 'readonly',
        prec: 'readonly',
        repeat: 'readonly',
        repeat1: 'readonly',
        seq: 'readonly',
        token: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      '@stylistic/eol-last': ['error', 'always'],
      '@stylistic/function-call-spacing': ['error', 'never'],
      '@stylistic/linebreak-style': ['error', 'unix'],
      '@stylistic/padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: '*', next: 'return' },
      ],
      '@stylistic/switch-colon-spacing': [
        'error',
        { after: true, before: false },
      ],
      'accessor-pairs': [
        'error',
        { getWithoutSet: false, setWithoutGet: true },
      ],
      'array-callback-return': ['error', { allowImplicit: false }],
      'arrow-body-style': [
        'error',
        'as-needed',
        { requireReturnForObjectLiteral: false },
      ],
      curly: ['error', 'all'],
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'error',
      eqeqeq: ['error', 'always'],
      'grouped-accessor-pairs': ['error', 'getBeforeSet'],
      'new-cap': 'error',
      'no-array-constructor': 'error',
      'no-constructor-return': 'error',
      'no-duplicate-imports': ['error', { includeExports: true }],
      'no-empty-function': 'error',
      'no-empty-static-block': 'error',
      'no-eq-null': 'error',
      'no-eval': ['error', { allowIndirect: false }],
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-label-var': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-multi-assign': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-new': 'error',
      'no-object-constructor': 'error',
      'no-octal-escape': 'error',
      'no-promise-executor-return': 'error',
      'no-return-assign': 'error',
      'no-self-compare': 'error',
      'no-shadow': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-unassigned-vars': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-unreachable-loop': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^\\$$' }],
      'no-useless-assignment': 'error',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      radix: 'error',
      'require-await': 'error',
      yoda: ['error', 'never'],
    },
  },
])
