#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 145
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 2
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5

enum {
  sym__variable_identifier = 1,
  anon_sym_module = 2,
  aux_sym_module_identifier_token1 = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  sym_all_constructors = 7,
  anon_sym_where = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_import = 11,
  anon_sym_qualified = 12,
  anon_sym_as = 13,
  anon_sym_hiding = 14,
  sym_variable_operator = 15,
  sym__terminal = 16,
  sym_comment = 17,
  sym_cpp_directive = 18,
  sym_pragma = 19,
  anon_sym_DASH_GT = 20,
  sym__layout_semicolon = 21,
  sym__layout_open_brace = 22,
  sym__layout_close_brace = 23,
  sym__qualified_module_dot = 24,
  sym__initialize_layout = 25,
  sym_module = 26,
  sym_module_identifier = 27,
  sym_qualified_module_identifier = 28,
  sym__qualified_module_identifier = 29,
  sym_exports = 30,
  sym_export = 31,
  sym_module_export = 32,
  sym__top_where = 33,
  sym__top_declarations = 34,
  sym__top_declaration = 35,
  sym_import_declaration = 36,
  sym__import_declaration = 37,
  sym_import_alias = 38,
  sym_import_spec = 39,
  sym_hiding_import_spec = 40,
  sym_import = 41,
  sym_variable_identifier = 42,
  sym_qualified_variable_identifier = 43,
  sym__qualified_variable_identifier = 44,
  sym_qualified_variable_operator = 45,
  sym__qualified_variable_operator = 46,
  sym__variable = 47,
  sym__qualified_variable = 48,
  sym__label = 49,
  sym_type_identifier = 50,
  sym_qualified_type_identifier = 51,
  sym__qualified_type_identifier = 52,
  sym_constructor_identifier = 53,
  aux_sym_module_repeat1 = 54,
  aux_sym_qualified_module_identifier_repeat1 = 55,
  aux_sym_exports_repeat1 = 56,
  aux_sym_export_repeat1 = 57,
  aux_sym__top_declarations_repeat1 = 58,
  aux_sym_import_spec_repeat1 = 59,
  alias_sym_label_identifier = 60,
  alias_sym_label_operator = 61,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__variable_identifier] = "_variable_identifier",
  [anon_sym_module] = "module",
  [aux_sym_module_identifier_token1] = "module_identifier_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_all_constructors] = "all_constructors",
  [anon_sym_where] = "where",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_import] = "import",
  [anon_sym_qualified] = "qualified",
  [anon_sym_as] = "as",
  [anon_sym_hiding] = "hiding",
  [sym_variable_operator] = "variable_operator",
  [sym__terminal] = "_terminal",
  [sym_comment] = "comment",
  [sym_cpp_directive] = "cpp_directive",
  [sym_pragma] = "pragma",
  [anon_sym_DASH_GT] = "->",
  [sym__layout_semicolon] = "_layout_semicolon",
  [sym__layout_open_brace] = "_layout_open_brace",
  [sym__layout_close_brace] = "_layout_close_brace",
  [sym__qualified_module_dot] = "_qualified_module_dot",
  [sym__initialize_layout] = "_initialize_layout",
  [sym_module] = "module",
  [sym_module_identifier] = "module_identifier",
  [sym_qualified_module_identifier] = "qualified_module_identifier",
  [sym__qualified_module_identifier] = "_qualified_module_identifier",
  [sym_exports] = "exports",
  [sym_export] = "export",
  [sym_module_export] = "module_export",
  [sym__top_where] = "_top_where",
  [sym__top_declarations] = "_top_declarations",
  [sym__top_declaration] = "_top_declaration",
  [sym_import_declaration] = "import_declaration",
  [sym__import_declaration] = "_import_declaration",
  [sym_import_alias] = "import_alias",
  [sym_import_spec] = "import_spec",
  [sym_hiding_import_spec] = "hiding_import_spec",
  [sym_import] = "import",
  [sym_variable_identifier] = "variable_identifier",
  [sym_qualified_variable_identifier] = "qualified_variable_identifier",
  [sym__qualified_variable_identifier] = "_qualified_variable_identifier",
  [sym_qualified_variable_operator] = "qualified_variable_operator",
  [sym__qualified_variable_operator] = "_qualified_variable_operator",
  [sym__variable] = "_variable",
  [sym__qualified_variable] = "_qualified_variable",
  [sym__label] = "_label",
  [sym_type_identifier] = "type_identifier",
  [sym_qualified_type_identifier] = "qualified_type_identifier",
  [sym__qualified_type_identifier] = "_qualified_type_identifier",
  [sym_constructor_identifier] = "constructor_identifier",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_qualified_module_identifier_repeat1] = "qualified_module_identifier_repeat1",
  [aux_sym_exports_repeat1] = "exports_repeat1",
  [aux_sym_export_repeat1] = "export_repeat1",
  [aux_sym__top_declarations_repeat1] = "_top_declarations_repeat1",
  [aux_sym_import_spec_repeat1] = "import_spec_repeat1",
  [alias_sym_label_identifier] = "label_identifier",
  [alias_sym_label_operator] = "label_operator",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__variable_identifier] = sym__variable_identifier,
  [anon_sym_module] = anon_sym_module,
  [aux_sym_module_identifier_token1] = aux_sym_module_identifier_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_all_constructors] = sym_all_constructors,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_qualified] = anon_sym_qualified,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_hiding] = anon_sym_hiding,
  [sym_variable_operator] = sym_variable_operator,
  [sym__terminal] = sym__terminal,
  [sym_comment] = sym_comment,
  [sym_cpp_directive] = sym_cpp_directive,
  [sym_pragma] = sym_pragma,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym__layout_semicolon] = sym__layout_semicolon,
  [sym__layout_open_brace] = sym__layout_open_brace,
  [sym__layout_close_brace] = sym__layout_close_brace,
  [sym__qualified_module_dot] = sym__qualified_module_dot,
  [sym__initialize_layout] = sym__initialize_layout,
  [sym_module] = sym_module,
  [sym_module_identifier] = sym_module_identifier,
  [sym_qualified_module_identifier] = sym_qualified_module_identifier,
  [sym__qualified_module_identifier] = sym__qualified_module_identifier,
  [sym_exports] = sym_exports,
  [sym_export] = sym_export,
  [sym_module_export] = sym_module_export,
  [sym__top_where] = sym__top_where,
  [sym__top_declarations] = sym__top_declarations,
  [sym__top_declaration] = sym__top_declaration,
  [sym_import_declaration] = sym_import_declaration,
  [sym__import_declaration] = sym__import_declaration,
  [sym_import_alias] = sym_import_alias,
  [sym_import_spec] = sym_import_spec,
  [sym_hiding_import_spec] = sym_hiding_import_spec,
  [sym_import] = sym_import,
  [sym_variable_identifier] = sym_variable_identifier,
  [sym_qualified_variable_identifier] = sym_qualified_variable_identifier,
  [sym__qualified_variable_identifier] = sym__qualified_variable_identifier,
  [sym_qualified_variable_operator] = sym_qualified_variable_operator,
  [sym__qualified_variable_operator] = sym__qualified_variable_operator,
  [sym__variable] = sym__variable,
  [sym__qualified_variable] = sym__qualified_variable,
  [sym__label] = sym__label,
  [sym_type_identifier] = sym_type_identifier,
  [sym_qualified_type_identifier] = sym_qualified_type_identifier,
  [sym__qualified_type_identifier] = sym__qualified_type_identifier,
  [sym_constructor_identifier] = sym_constructor_identifier,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_qualified_module_identifier_repeat1] = aux_sym_qualified_module_identifier_repeat1,
  [aux_sym_exports_repeat1] = aux_sym_exports_repeat1,
  [aux_sym_export_repeat1] = aux_sym_export_repeat1,
  [aux_sym__top_declarations_repeat1] = aux_sym__top_declarations_repeat1,
  [aux_sym_import_spec_repeat1] = aux_sym_import_spec_repeat1,
  [alias_sym_label_identifier] = alias_sym_label_identifier,
  [alias_sym_label_operator] = alias_sym_label_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__variable_identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_module_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_all_constructors] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_qualified] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hiding] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__terminal] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_cpp_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_pragma] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__layout_semicolon] = {
    .visible = false,
    .named = true,
  },
  [sym__layout_open_brace] = {
    .visible = false,
    .named = true,
  },
  [sym__layout_close_brace] = {
    .visible = false,
    .named = true,
  },
  [sym__qualified_module_dot] = {
    .visible = false,
    .named = true,
  },
  [sym__initialize_layout] = {
    .visible = false,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_module_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_module_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__qualified_module_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_exports] = {
    .visible = true,
    .named = true,
  },
  [sym_export] = {
    .visible = true,
    .named = true,
  },
  [sym_module_export] = {
    .visible = true,
    .named = true,
  },
  [sym__top_where] = {
    .visible = false,
    .named = true,
  },
  [sym__top_declarations] = {
    .visible = false,
    .named = true,
  },
  [sym__top_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__import_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_import_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_import_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_hiding_import_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_variable_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__qualified_variable_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_qualified_variable_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__qualified_variable_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__variable] = {
    .visible = false,
    .named = true,
  },
  [sym__qualified_variable] = {
    .visible = false,
    .named = true,
  },
  [sym__label] = {
    .visible = false,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__qualified_type_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_constructor_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_module_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exports_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_export_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__top_declarations_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_spec_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_label_identifier] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_label_operator] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_label_identifier,
  },
  [2] = {
    [1] = alias_sym_label_operator,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '\\') SKIP(15)
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(17);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '\\') SKIP(12)
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(17);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '.' ||
          lookahead == '/' ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(4);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(10);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(13);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(14);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'n') SKIP(1)
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(31);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(34);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == 'n') SKIP(0)
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_module_identifier_token1);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '.') ADVANCE(11);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_all_constructors);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__variable_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_variable_operator);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '.' ||
          lookahead == '/' ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_variable_operator);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_variable_operator);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_variable_operator);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__terminal);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_cpp_directive);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_pragma);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\\') SKIP(1)
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'h') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 'q') ADVANCE(6);
      if (lookahead == 'w') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') SKIP(0)
      END_STATE();
    case 2:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_hiding);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 34:
      if (lookahead == 'd') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_qualified);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1, .external_lex_state = 3},
  [7] = {.lex_state = 1, .external_lex_state = 3},
  [8] = {.lex_state = 1, .external_lex_state = 3},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1, .external_lex_state = 4},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1, .external_lex_state = 5},
  [25] = {.lex_state = 1, .external_lex_state = 5},
  [26] = {.lex_state = 1, .external_lex_state = 5},
  [27] = {.lex_state = 1, .external_lex_state = 4},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0, .external_lex_state = 6},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1, .external_lex_state = 4},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0, .external_lex_state = 7},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 4},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0, .external_lex_state = 4},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 4},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0, .external_lex_state = 4},
  [100] = {.lex_state = 0, .external_lex_state = 4},
  [101] = {.lex_state = 0, .external_lex_state = 4},
  [102] = {.lex_state = 0, .external_lex_state = 4},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0, .external_lex_state = 4},
  [107] = {.lex_state = 0, .external_lex_state = 4},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0, .external_lex_state = 4},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0, .external_lex_state = 6},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0, .external_lex_state = 3},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 0, .external_lex_state = 3},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 0, .external_lex_state = 3},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0, .external_lex_state = 3},
  [134] = {.lex_state = 0, .external_lex_state = 3},
  [135] = {.lex_state = 1},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 1},
};

enum {
  ts_external_token__layout_semicolon = 0,
  ts_external_token__layout_open_brace = 1,
  ts_external_token__layout_close_brace = 2,
  ts_external_token_DASH_GT = 3,
  ts_external_token__qualified_module_dot = 4,
  ts_external_token__initialize_layout = 5,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__layout_semicolon] = sym__layout_semicolon,
  [ts_external_token__layout_open_brace] = sym__layout_open_brace,
  [ts_external_token__layout_close_brace] = sym__layout_close_brace,
  [ts_external_token_DASH_GT] = anon_sym_DASH_GT,
  [ts_external_token__qualified_module_dot] = sym__qualified_module_dot,
  [ts_external_token__initialize_layout] = sym__initialize_layout,
};

static bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__layout_semicolon] = true,
    [ts_external_token__layout_open_brace] = true,
    [ts_external_token__layout_close_brace] = true,
    [ts_external_token_DASH_GT] = true,
    [ts_external_token__qualified_module_dot] = true,
    [ts_external_token__initialize_layout] = true,
  },
  [2] = {
    [ts_external_token__initialize_layout] = true,
  },
  [3] = {
    [ts_external_token__qualified_module_dot] = true,
  },
  [4] = {
    [ts_external_token__layout_semicolon] = true,
  },
  [5] = {
    [ts_external_token__layout_semicolon] = true,
    [ts_external_token__qualified_module_dot] = true,
  },
  [6] = {
    [ts_external_token__layout_close_brace] = true,
  },
  [7] = {
    [ts_external_token__layout_open_brace] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__variable_identifier] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [aux_sym_module_identifier_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_all_constructors] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_qualified] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_hiding] = ACTIONS(1),
    [sym__terminal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_cpp_directive] = ACTIONS(3),
    [sym_pragma] = ACTIONS(3),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym__layout_semicolon] = ACTIONS(1),
    [sym__layout_open_brace] = ACTIONS(1),
    [sym__layout_close_brace] = ACTIONS(1),
    [sym__qualified_module_dot] = ACTIONS(1),
    [sym__initialize_layout] = ACTIONS(1),
  },
  [1] = {
    [sym_module] = STATE(132),
    [anon_sym_module] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_cpp_directive] = ACTIONS(3),
    [sym_pragma] = ACTIONS(3),
    [sym__initialize_layout] = ACTIONS(7),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(9), 1,
      sym__variable_identifier,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(13), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_COMMA,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(63), 1,
      sym_export,
    STATE(133), 1,
      sym_module_identifier,
    STATE(128), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    STATE(46), 3,
      sym_type_identifier,
      sym_qualified_type_identifier,
      sym__qualified_type_identifier,
    STATE(114), 5,
      sym_module_export,
      sym_variable_identifier,
      sym_qualified_variable_identifier,
      sym__qualified_variable_identifier,
      sym__qualified_variable,
  [49] = 12,
    ACTIONS(9), 1,
      sym__variable_identifier,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(13), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(93), 1,
      sym_export,
    STATE(133), 1,
      sym_module_identifier,
    STATE(128), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    STATE(46), 3,
      sym_type_identifier,
      sym_qualified_type_identifier,
      sym__qualified_type_identifier,
    STATE(114), 5,
      sym_module_export,
      sym_variable_identifier,
      sym_qualified_variable_identifier,
      sym__qualified_variable_identifier,
      sym__qualified_variable,
  [95] = 12,
    ACTIONS(9), 1,
      sym__variable_identifier,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(13), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(93), 1,
      sym_export,
    STATE(133), 1,
      sym_module_identifier,
    STATE(128), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    STATE(46), 3,
      sym_type_identifier,
      sym_qualified_type_identifier,
      sym__qualified_type_identifier,
    STATE(114), 5,
      sym_module_export,
      sym_variable_identifier,
      sym_qualified_variable_identifier,
      sym__qualified_variable_identifier,
      sym__qualified_variable,
  [141] = 11,
    ACTIONS(9), 1,
      sym__variable_identifier,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(13), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(54), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(93), 1,
      sym_export,
    STATE(133), 1,
      sym_module_identifier,
    STATE(128), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    STATE(46), 3,
      sym_type_identifier,
      sym_qualified_type_identifier,
      sym__qualified_type_identifier,
    STATE(114), 5,
      sym_module_export,
      sym_variable_identifier,
      sym_qualified_variable_identifier,
      sym__qualified_variable_identifier,
      sym__qualified_variable,
  [184] = 3,
    ACTIONS(27), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(25), 9,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_as,
      anon_sym_hiding,
      sym__terminal,
  [204] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(29), 10,
      sym__qualified_module_dot,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_as,
      anon_sym_hiding,
      sym__terminal,
  [222] = 3,
    ACTIONS(27), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(31), 9,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_as,
      anon_sym_hiding,
      sym__terminal,
  [242] = 8,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(35), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_type_identifier,
    STATE(73), 1,
      sym_import,
    STATE(118), 2,
      sym_variable_identifier,
      sym__variable,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [270] = 8,
    ACTIONS(41), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(43), 1,
      anon_sym_qualified,
    STATE(24), 1,
      sym_module_identifier,
    STATE(27), 1,
      sym_import_alias,
    STATE(56), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(87), 1,
      sym__import_declaration,
    STATE(21), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [298] = 8,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(35), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_type_identifier,
    STATE(55), 1,
      sym_import,
    STATE(118), 2,
      sym_variable_identifier,
      sym__variable,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [326] = 8,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(35), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_type_identifier,
    STATE(51), 1,
      sym_import,
    STATE(118), 2,
      sym_variable_identifier,
      sym__variable,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [354] = 7,
    ACTIONS(49), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(51), 1,
      sym_variable_operator,
    STATE(54), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(133), 1,
      sym_module_identifier,
    STATE(120), 2,
      sym_qualified_variable_operator,
      sym__qualified_variable_operator,
    STATE(121), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(53), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [380] = 8,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(57), 1,
      anon_sym_qualified,
    STATE(8), 1,
      sym_module_identifier,
    STATE(18), 1,
      sym_import_alias,
    STATE(53), 1,
      sym__import_declaration,
    STATE(60), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(15), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [408] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_as,
    ACTIONS(65), 1,
      anon_sym_hiding,
    STATE(61), 2,
      sym_import_spec,
      sym_hiding_import_spec,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(61), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [432] = 8,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(35), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_type_identifier,
    STATE(71), 1,
      sym_import,
    STATE(118), 2,
      sym_variable_identifier,
      sym__variable,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [460] = 7,
    ACTIONS(41), 1,
      aux_sym_module_identifier_token1,
    STATE(24), 1,
      sym_module_identifier,
    STATE(27), 1,
      sym_import_alias,
    STATE(56), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(99), 1,
      sym__import_declaration,
    STATE(21), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [485] = 5,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_hiding,
    STATE(61), 2,
      sym_import_spec,
      sym_hiding_import_spec,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(61), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [506] = 7,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(69), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_variable_identifier,
    STATE(80), 2,
      sym__label,
      sym_constructor_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [531] = 7,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    STATE(8), 1,
      sym_module_identifier,
    STATE(18), 1,
      sym_import_alias,
    STATE(57), 1,
      sym__import_declaration,
    STATE(60), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(15), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [556] = 6,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_as,
    ACTIONS(79), 1,
      anon_sym_hiding,
    ACTIONS(61), 2,
      sym__layout_semicolon,
      sym__terminal,
    STATE(102), 2,
      sym_import_spec,
      sym_hiding_import_spec,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [579] = 7,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(69), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_variable_identifier,
    STATE(77), 2,
      sym__label,
      sym_constructor_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [604] = 7,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(35), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_type_identifier,
    STATE(91), 1,
      sym_import,
    STATE(118), 2,
      sym_variable_identifier,
      sym__variable,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [629] = 3,
    ACTIONS(27), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(31), 5,
      sym__layout_semicolon,
      anon_sym_LPAREN,
      anon_sym_as,
      anon_sym_hiding,
      sym__terminal,
  [645] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(29), 6,
      sym__layout_semicolon,
      sym__qualified_module_dot,
      anon_sym_LPAREN,
      anon_sym_as,
      anon_sym_hiding,
      sym__terminal,
  [659] = 3,
    ACTIONS(27), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(25), 5,
      sym__layout_semicolon,
      anon_sym_LPAREN,
      anon_sym_as,
      anon_sym_hiding,
      sym__terminal,
  [675] = 5,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      anon_sym_hiding,
    ACTIONS(61), 2,
      sym__layout_semicolon,
      sym__terminal,
    STATE(102), 2,
      sym_import_spec,
      sym_hiding_import_spec,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [695] = 6,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(69), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_variable_identifier,
    STATE(109), 2,
      sym__label,
      sym_constructor_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [717] = 5,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    STATE(8), 1,
      sym_module_identifier,
    STATE(60), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(116), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [736] = 5,
    ACTIONS(83), 1,
      anon_sym_import,
    ACTIONS(85), 1,
      sym__layout_close_brace,
    STATE(35), 1,
      aux_sym_module_repeat1,
    STATE(101), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [755] = 5,
    ACTIONS(83), 1,
      anon_sym_import,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      aux_sym_module_repeat1,
    STATE(86), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [774] = 4,
    ACTIONS(29), 1,
      sym__qualified_module_dot,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(91), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_all_constructors,
  [791] = 5,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 1,
      anon_sym_import,
    STATE(33), 1,
      aux_sym_module_repeat1,
    STATE(86), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [810] = 5,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      anon_sym_import,
    STATE(39), 1,
      aux_sym__top_declarations_repeat1,
    STATE(64), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [829] = 5,
    ACTIONS(83), 1,
      anon_sym_import,
    ACTIONS(98), 1,
      sym__layout_close_brace,
    STATE(38), 1,
      aux_sym_module_repeat1,
    STATE(101), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [848] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(102), 5,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_hiding,
      sym__terminal,
  [861] = 5,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    STATE(8), 1,
      sym_module_identifier,
    STATE(60), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(48), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [880] = 5,
    ACTIONS(93), 1,
      sym__layout_close_brace,
    ACTIONS(95), 1,
      anon_sym_import,
    STATE(38), 1,
      aux_sym_module_repeat1,
    STATE(101), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [899] = 5,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(106), 1,
      anon_sym_import,
    STATE(39), 1,
      aux_sym__top_declarations_repeat1,
    STATE(64), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [918] = 5,
    ACTIONS(83), 1,
      anon_sym_import,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      aux_sym_module_repeat1,
    STATE(86), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [937] = 5,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      anon_sym_import,
    STATE(34), 1,
      aux_sym__top_declarations_repeat1,
    STATE(64), 2,
      sym__top_declaration,
      sym_import_declaration,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [956] = 5,
    ACTIONS(41), 1,
      aux_sym_module_identifier_token1,
    STATE(24), 1,
      sym_module_identifier,
    STATE(56), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(49), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [975] = 5,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    STATE(8), 1,
      sym_module_identifier,
    STATE(60), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(36), 2,
      sym_qualified_module_identifier,
      sym__qualified_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [994] = 5,
    ACTIONS(33), 1,
      sym__variable_identifier,
    ACTIONS(35), 1,
      aux_sym_module_identifier_token1,
    STATE(47), 1,
      sym_type_identifier,
    STATE(97), 1,
      sym_variable_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1012] = 3,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(91), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_all_constructors,
  [1026] = 4,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      sym_all_constructors,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1042] = 3,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(119), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_all_constructors,
  [1056] = 5,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_where,
    STATE(98), 1,
      sym_exports,
    STATE(138), 1,
      sym__top_where,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1074] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(102), 4,
      sym__layout_semicolon,
      anon_sym_LPAREN,
      anon_sym_hiding,
      sym__terminal,
  [1086] = 4,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      sym_all_constructors,
    ACTIONS(127), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1102] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1117] = 4,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_export_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1132] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(140), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1143] = 4,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    STATE(82), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(134), 1,
      sym_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1158] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1173] = 4,
    ACTIONS(41), 1,
      aux_sym_module_identifier_token1,
    STATE(26), 1,
      sym_module_identifier,
    STATE(82), 1,
      aux_sym_qualified_module_identifier_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1188] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(144), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1199] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1214] = 4,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_exports_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1229] = 4,
    ACTIONS(55), 1,
      aux_sym_module_identifier_token1,
    STATE(6), 1,
      sym_module_identifier,
    STATE(82), 1,
      aux_sym_qualified_module_identifier_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1244] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(150), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1255] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(152), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1266] = 4,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_exports_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1281] = 3,
    ACTIONS(160), 1,
      sym__terminal,
    ACTIONS(158), 2,
      anon_sym_RBRACE,
      anon_sym_import,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1294] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(162), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1305] = 4,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 1,
      sym__layout_open_brace,
    STATE(126), 1,
      sym__top_declarations,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1320] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(168), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1331] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_export_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1346] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1361] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(176), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1372] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1387] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_export_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1402] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1417] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(184), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1428] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1443] = 4,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_exports_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1458] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_export_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1473] = 2,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
    ACTIONS(195), 3,
      anon_sym_RBRACE,
      anon_sym_import,
      sym__terminal,
  [1484] = 4,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1499] = 4,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_export_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1514] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_import_spec_repeat1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1529] = 4,
    ACTIONS(206), 1,
      aux_sym_module_identifier_token1,
    STATE(82), 1,
      aux_sym_qualified_module_identifier_repeat1,
    STATE(124), 1,
      sym_module_identifier,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1544] = 2,
    ACTIONS(209), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1554] = 2,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1564] = 2,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1574] = 2,
    ACTIONS(215), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1584] = 2,
    ACTIONS(140), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1594] = 2,
    ACTIONS(104), 2,
      anon_sym_RBRACE,
      anon_sym_import,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1604] = 2,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      anon_sym_import,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1614] = 2,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1624] = 2,
    ACTIONS(200), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1634] = 2,
    ACTIONS(176), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1644] = 2,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1654] = 2,
    ACTIONS(219), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1664] = 2,
    ACTIONS(221), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1674] = 2,
    ACTIONS(184), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1684] = 2,
    ACTIONS(223), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1694] = 3,
    ACTIONS(123), 1,
      anon_sym_where,
    STATE(125), 1,
      sym__top_where,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1706] = 2,
    ACTIONS(144), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1716] = 2,
    ACTIONS(152), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1726] = 2,
    ACTIONS(225), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1736] = 2,
    ACTIONS(150), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1746] = 2,
    ACTIONS(227), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1756] = 2,
    ACTIONS(229), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1766] = 2,
    ACTIONS(231), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1776] = 2,
    ACTIONS(168), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1786] = 2,
    ACTIONS(195), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1796] = 2,
    ACTIONS(233), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1806] = 2,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1816] = 2,
    ACTIONS(235), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1826] = 2,
    ACTIONS(162), 2,
      sym__layout_semicolon,
      sym__terminal,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1836] = 2,
    ACTIONS(237), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1846] = 2,
    ACTIONS(239), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1856] = 2,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1866] = 2,
    ACTIONS(241), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1876] = 2,
    ACTIONS(243), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1886] = 2,
    ACTIONS(93), 2,
      sym__layout_close_brace,
      anon_sym_import,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1896] = 2,
    ACTIONS(127), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1906] = 2,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1915] = 2,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1924] = 2,
    ACTIONS(249), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1933] = 2,
    ACTIONS(251), 1,
      anon_sym_where,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1942] = 2,
    ACTIONS(253), 1,
      sym_variable_operator,
    ACTIONS(53), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1951] = 2,
    ACTIONS(27), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1960] = 2,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1969] = 2,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1978] = 2,
    ACTIONS(259), 1,
      sym_variable_operator,
    ACTIONS(53), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1987] = 2,
    ACTIONS(261), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [1996] = 2,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2005] = 2,
    ACTIONS(265), 1,
      anon_sym_where,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2014] = 2,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2023] = 2,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2032] = 2,
    ACTIONS(269), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2041] = 2,
    ACTIONS(272), 1,
      sym__qualified_module_dot,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2050] = 2,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2059] = 2,
    ACTIONS(277), 1,
      sym_variable_operator,
    ACTIONS(53), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2068] = 2,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2077] = 2,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2086] = 2,
    ACTIONS(283), 1,
      anon_sym_where,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2095] = 2,
    ACTIONS(285), 1,
      aux_sym_module_identifier_token1,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2104] = 2,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2113] = 2,
    ACTIONS(289), 1,
      anon_sym_where,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2122] = 2,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
  [2131] = 2,
    ACTIONS(293), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 3,
      sym_comment,
      sym_cpp_directive,
      sym_pragma,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 95,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 184,
  [SMALL_STATE(7)] = 204,
  [SMALL_STATE(8)] = 222,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 270,
  [SMALL_STATE(11)] = 298,
  [SMALL_STATE(12)] = 326,
  [SMALL_STATE(13)] = 354,
  [SMALL_STATE(14)] = 380,
  [SMALL_STATE(15)] = 408,
  [SMALL_STATE(16)] = 432,
  [SMALL_STATE(17)] = 460,
  [SMALL_STATE(18)] = 485,
  [SMALL_STATE(19)] = 506,
  [SMALL_STATE(20)] = 531,
  [SMALL_STATE(21)] = 556,
  [SMALL_STATE(22)] = 579,
  [SMALL_STATE(23)] = 604,
  [SMALL_STATE(24)] = 629,
  [SMALL_STATE(25)] = 645,
  [SMALL_STATE(26)] = 659,
  [SMALL_STATE(27)] = 675,
  [SMALL_STATE(28)] = 695,
  [SMALL_STATE(29)] = 717,
  [SMALL_STATE(30)] = 736,
  [SMALL_STATE(31)] = 755,
  [SMALL_STATE(32)] = 774,
  [SMALL_STATE(33)] = 791,
  [SMALL_STATE(34)] = 810,
  [SMALL_STATE(35)] = 829,
  [SMALL_STATE(36)] = 848,
  [SMALL_STATE(37)] = 861,
  [SMALL_STATE(38)] = 880,
  [SMALL_STATE(39)] = 899,
  [SMALL_STATE(40)] = 918,
  [SMALL_STATE(41)] = 937,
  [SMALL_STATE(42)] = 956,
  [SMALL_STATE(43)] = 975,
  [SMALL_STATE(44)] = 994,
  [SMALL_STATE(45)] = 1012,
  [SMALL_STATE(46)] = 1026,
  [SMALL_STATE(47)] = 1042,
  [SMALL_STATE(48)] = 1056,
  [SMALL_STATE(49)] = 1074,
  [SMALL_STATE(50)] = 1086,
  [SMALL_STATE(51)] = 1102,
  [SMALL_STATE(52)] = 1117,
  [SMALL_STATE(53)] = 1132,
  [SMALL_STATE(54)] = 1143,
  [SMALL_STATE(55)] = 1158,
  [SMALL_STATE(56)] = 1173,
  [SMALL_STATE(57)] = 1188,
  [SMALL_STATE(58)] = 1199,
  [SMALL_STATE(59)] = 1214,
  [SMALL_STATE(60)] = 1229,
  [SMALL_STATE(61)] = 1244,
  [SMALL_STATE(62)] = 1255,
  [SMALL_STATE(63)] = 1266,
  [SMALL_STATE(64)] = 1281,
  [SMALL_STATE(65)] = 1294,
  [SMALL_STATE(66)] = 1305,
  [SMALL_STATE(67)] = 1320,
  [SMALL_STATE(68)] = 1331,
  [SMALL_STATE(69)] = 1346,
  [SMALL_STATE(70)] = 1361,
  [SMALL_STATE(71)] = 1372,
  [SMALL_STATE(72)] = 1387,
  [SMALL_STATE(73)] = 1402,
  [SMALL_STATE(74)] = 1417,
  [SMALL_STATE(75)] = 1428,
  [SMALL_STATE(76)] = 1443,
  [SMALL_STATE(77)] = 1458,
  [SMALL_STATE(78)] = 1473,
  [SMALL_STATE(79)] = 1484,
  [SMALL_STATE(80)] = 1499,
  [SMALL_STATE(81)] = 1514,
  [SMALL_STATE(82)] = 1529,
  [SMALL_STATE(83)] = 1544,
  [SMALL_STATE(84)] = 1554,
  [SMALL_STATE(85)] = 1564,
  [SMALL_STATE(86)] = 1574,
  [SMALL_STATE(87)] = 1584,
  [SMALL_STATE(88)] = 1594,
  [SMALL_STATE(89)] = 1604,
  [SMALL_STATE(90)] = 1614,
  [SMALL_STATE(91)] = 1624,
  [SMALL_STATE(92)] = 1634,
  [SMALL_STATE(93)] = 1644,
  [SMALL_STATE(94)] = 1654,
  [SMALL_STATE(95)] = 1664,
  [SMALL_STATE(96)] = 1674,
  [SMALL_STATE(97)] = 1684,
  [SMALL_STATE(98)] = 1694,
  [SMALL_STATE(99)] = 1706,
  [SMALL_STATE(100)] = 1716,
  [SMALL_STATE(101)] = 1726,
  [SMALL_STATE(102)] = 1736,
  [SMALL_STATE(103)] = 1746,
  [SMALL_STATE(104)] = 1756,
  [SMALL_STATE(105)] = 1766,
  [SMALL_STATE(106)] = 1776,
  [SMALL_STATE(107)] = 1786,
  [SMALL_STATE(108)] = 1796,
  [SMALL_STATE(109)] = 1806,
  [SMALL_STATE(110)] = 1816,
  [SMALL_STATE(111)] = 1826,
  [SMALL_STATE(112)] = 1836,
  [SMALL_STATE(113)] = 1846,
  [SMALL_STATE(114)] = 1856,
  [SMALL_STATE(115)] = 1866,
  [SMALL_STATE(116)] = 1876,
  [SMALL_STATE(117)] = 1886,
  [SMALL_STATE(118)] = 1896,
  [SMALL_STATE(119)] = 1906,
  [SMALL_STATE(120)] = 1915,
  [SMALL_STATE(121)] = 1924,
  [SMALL_STATE(122)] = 1933,
  [SMALL_STATE(123)] = 1942,
  [SMALL_STATE(124)] = 1951,
  [SMALL_STATE(125)] = 1960,
  [SMALL_STATE(126)] = 1969,
  [SMALL_STATE(127)] = 1978,
  [SMALL_STATE(128)] = 1987,
  [SMALL_STATE(129)] = 1996,
  [SMALL_STATE(130)] = 2005,
  [SMALL_STATE(131)] = 2014,
  [SMALL_STATE(132)] = 2023,
  [SMALL_STATE(133)] = 2032,
  [SMALL_STATE(134)] = 2041,
  [SMALL_STATE(135)] = 2050,
  [SMALL_STATE(136)] = 2059,
  [SMALL_STATE(137)] = 2068,
  [SMALL_STATE(138)] = 2077,
  [SMALL_STATE(139)] = 2086,
  [SMALL_STATE(140)] = 2095,
  [SMALL_STATE(141)] = 2104,
  [SMALL_STATE(142)] = 2113,
  [SMALL_STATE(143)] = 2122,
  [SMALL_STATE(144)] = 2131,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, SHIFT_EXTRA(),
  [5] = {.count = 1, .reusable = true}, SHIFT(37),
  [7] = {.count = 1, .reusable = true}, SHIFT(31),
  [9] = {.count = 1, .reusable = false}, SHIFT(104),
  [11] = {.count = 1, .reusable = false}, SHIFT(29),
  [13] = {.count = 1, .reusable = true}, SHIFT(32),
  [15] = {.count = 1, .reusable = true}, SHIFT(13),
  [17] = {.count = 1, .reusable = true}, SHIFT(131),
  [19] = {.count = 1, .reusable = true}, SHIFT(130),
  [21] = {.count = 1, .reusable = true}, SHIFT(139),
  [23] = {.count = 1, .reusable = true}, SHIFT(142),
  [25] = {.count = 1, .reusable = true}, REDUCE(sym_qualified_module_identifier, 2),
  [27] = {.count = 1, .reusable = true}, SHIFT(140),
  [29] = {.count = 1, .reusable = true}, REDUCE(sym_module_identifier, 1),
  [31] = {.count = 1, .reusable = true}, REDUCE(sym__qualified_module_identifier, 1),
  [33] = {.count = 1, .reusable = true}, SHIFT(104),
  [35] = {.count = 1, .reusable = true}, SHIFT(45),
  [37] = {.count = 1, .reusable = true}, SHIFT(123),
  [39] = {.count = 1, .reusable = true}, SHIFT(106),
  [41] = {.count = 1, .reusable = true}, SHIFT(25),
  [43] = {.count = 1, .reusable = true}, SHIFT(17),
  [45] = {.count = 1, .reusable = true}, SHIFT(100),
  [47] = {.count = 1, .reusable = true}, SHIFT(62),
  [49] = {.count = 1, .reusable = false}, SHIFT(7),
  [51] = {.count = 1, .reusable = false}, SHIFT(120),
  [53] = {.count = 1, .reusable = false}, SHIFT_EXTRA(),
  [55] = {.count = 1, .reusable = true}, SHIFT(7),
  [57] = {.count = 1, .reusable = true}, SHIFT(20),
  [59] = {.count = 1, .reusable = true}, SHIFT(12),
  [61] = {.count = 1, .reusable = true}, REDUCE(sym__import_declaration, 1),
  [63] = {.count = 1, .reusable = true}, SHIFT(43),
  [65] = {.count = 1, .reusable = true}, SHIFT(144),
  [67] = {.count = 1, .reusable = true}, SHIFT(67),
  [69] = {.count = 1, .reusable = true}, SHIFT(84),
  [71] = {.count = 1, .reusable = true}, SHIFT(136),
  [73] = {.count = 1, .reusable = true}, SHIFT(94),
  [75] = {.count = 1, .reusable = true}, SHIFT(11),
  [77] = {.count = 1, .reusable = true}, SHIFT(42),
  [79] = {.count = 1, .reusable = true}, SHIFT(135),
  [81] = {.count = 1, .reusable = true}, SHIFT(113),
  [83] = {.count = 1, .reusable = true}, SHIFT(10),
  [85] = {.count = 1, .reusable = true}, SHIFT(129),
  [87] = {.count = 1, .reusable = true}, REDUCE(sym_module, 1),
  [89] = {.count = 1, .reusable = false}, REDUCE(sym_type_identifier, 1),
  [91] = {.count = 1, .reusable = true}, REDUCE(sym_type_identifier, 1),
  [93] = {.count = 1, .reusable = true}, REDUCE(aux_sym_module_repeat1, 2),
  [95] = {.count = 2, .reusable = true}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(10),
  [98] = {.count = 1, .reusable = true}, SHIFT(143),
  [100] = {.count = 1, .reusable = true}, SHIFT(14),
  [102] = {.count = 1, .reusable = true}, REDUCE(sym_import_alias, 3),
  [104] = {.count = 1, .reusable = true}, REDUCE(aux_sym__top_declarations_repeat1, 2),
  [106] = {.count = 2, .reusable = true}, REDUCE(aux_sym__top_declarations_repeat1, 2), SHIFT_REPEAT(14),
  [109] = {.count = 1, .reusable = true}, REDUCE(sym_module, 2),
  [111] = {.count = 1, .reusable = false}, SHIFT(22),
  [113] = {.count = 1, .reusable = true}, REDUCE(sym_export, 1),
  [115] = {.count = 1, .reusable = true}, SHIFT(115),
  [117] = {.count = 1, .reusable = false}, REDUCE(sym_qualified_type_identifier, 3),
  [119] = {.count = 1, .reusable = true}, REDUCE(sym_qualified_type_identifier, 3),
  [121] = {.count = 1, .reusable = true}, SHIFT(2),
  [123] = {.count = 1, .reusable = true}, SHIFT(66),
  [125] = {.count = 1, .reusable = false}, SHIFT(19),
  [127] = {.count = 1, .reusable = true}, REDUCE(sym_import, 1),
  [129] = {.count = 1, .reusable = true}, SHIFT(83),
  [131] = {.count = 1, .reusable = true}, SHIFT(23),
  [133] = {.count = 1, .reusable = true}, SHIFT(65),
  [135] = {.count = 2, .reusable = true}, REDUCE(aux_sym_export_repeat1, 2), SHIFT_REPEAT(28),
  [138] = {.count = 1, .reusable = true}, REDUCE(aux_sym_export_repeat1, 2),
  [140] = {.count = 1, .reusable = true}, REDUCE(sym_import_declaration, 2),
  [142] = {.count = 1, .reusable = true}, SHIFT(111),
  [144] = {.count = 1, .reusable = true}, REDUCE(sym_import_declaration, 3),
  [146] = {.count = 1, .reusable = true}, SHIFT(70),
  [148] = {.count = 1, .reusable = true}, SHIFT(3),
  [150] = {.count = 1, .reusable = true}, REDUCE(sym__import_declaration, 2),
  [152] = {.count = 1, .reusable = true}, REDUCE(sym_import_spec, 2),
  [154] = {.count = 1, .reusable = true}, SHIFT(4),
  [156] = {.count = 1, .reusable = true}, SHIFT(122),
  [158] = {.count = 1, .reusable = true}, REDUCE(aux_sym__top_declarations_repeat1, 1),
  [160] = {.count = 1, .reusable = true}, SHIFT(88),
  [162] = {.count = 1, .reusable = true}, REDUCE(sym_import_spec, 3),
  [164] = {.count = 1, .reusable = false}, SHIFT(41),
  [166] = {.count = 1, .reusable = true}, SHIFT(30),
  [168] = {.count = 1, .reusable = true}, REDUCE(sym_hiding_import_spec, 3),
  [170] = {.count = 1, .reusable = true}, SHIFT(28),
  [172] = {.count = 1, .reusable = true}, SHIFT(112),
  [174] = {.count = 1, .reusable = true}, SHIFT(92),
  [176] = {.count = 1, .reusable = true}, REDUCE(sym_import_spec, 4),
  [178] = {.count = 1, .reusable = true}, SHIFT(74),
  [180] = {.count = 1, .reusable = true}, SHIFT(110),
  [182] = {.count = 1, .reusable = true}, SHIFT(96),
  [184] = {.count = 1, .reusable = true}, REDUCE(sym_hiding_import_spec, 4),
  [186] = {.count = 1, .reusable = true}, SHIFT(78),
  [188] = {.count = 2, .reusable = true}, REDUCE(aux_sym_exports_repeat1, 2), SHIFT_REPEAT(5),
  [191] = {.count = 1, .reusable = true}, REDUCE(aux_sym_exports_repeat1, 2),
  [193] = {.count = 1, .reusable = true}, SHIFT(103),
  [195] = {.count = 1, .reusable = true}, REDUCE(sym_hiding_import_spec, 5),
  [197] = {.count = 2, .reusable = true}, REDUCE(aux_sym_import_spec_repeat1, 2), SHIFT_REPEAT(23),
  [200] = {.count = 1, .reusable = true}, REDUCE(aux_sym_import_spec_repeat1, 2),
  [202] = {.count = 1, .reusable = true}, SHIFT(105),
  [204] = {.count = 1, .reusable = true}, SHIFT(107),
  [206] = {.count = 2, .reusable = true}, REDUCE(aux_sym_qualified_module_identifier_repeat1, 2), SHIFT_REPEAT(7),
  [209] = {.count = 1, .reusable = true}, REDUCE(sym_import, 2),
  [211] = {.count = 1, .reusable = true}, REDUCE(sym_constructor_identifier, 1),
  [213] = {.count = 1, .reusable = true}, REDUCE(sym__label, 1, .production_id = 1),
  [215] = {.count = 1, .reusable = true}, SHIFT(89),
  [217] = {.count = 1, .reusable = true}, REDUCE(sym__variable, 3),
  [219] = {.count = 1, .reusable = true}, REDUCE(sym_import, 3),
  [221] = {.count = 1, .reusable = true}, REDUCE(sym__qualified_variable, 3),
  [223] = {.count = 1, .reusable = true}, REDUCE(sym_qualified_variable_identifier, 3),
  [225] = {.count = 1, .reusable = true}, SHIFT(117),
  [227] = {.count = 1, .reusable = true}, REDUCE(sym_export, 4),
  [229] = {.count = 1, .reusable = true}, REDUCE(sym_variable_identifier, 1),
  [231] = {.count = 1, .reusable = true}, REDUCE(sym_import, 4),
  [233] = {.count = 1, .reusable = true}, REDUCE(sym__label, 3, .production_id = 2),
  [235] = {.count = 1, .reusable = true}, REDUCE(sym_export, 5),
  [237] = {.count = 1, .reusable = true}, REDUCE(sym_import, 5),
  [239] = {.count = 1, .reusable = true}, REDUCE(sym_export, 3),
  [241] = {.count = 1, .reusable = true}, REDUCE(sym_export, 2),
  [243] = {.count = 1, .reusable = true}, REDUCE(sym_module_export, 2),
  [245] = {.count = 1, .reusable = true}, SHIFT(90),
  [247] = {.count = 1, .reusable = true}, SHIFT(95),
  [249] = {.count = 1, .reusable = true}, SHIFT(127),
  [251] = {.count = 1, .reusable = true}, REDUCE(sym_exports, 3),
  [253] = {.count = 1, .reusable = false}, SHIFT(119),
  [255] = {.count = 1, .reusable = true}, REDUCE(sym_module, 4),
  [257] = {.count = 1, .reusable = true}, REDUCE(sym__top_where, 2),
  [259] = {.count = 1, .reusable = false}, SHIFT(141),
  [261] = {.count = 1, .reusable = true}, SHIFT(44),
  [263] = {.count = 1, .reusable = true}, REDUCE(sym__top_declarations, 2),
  [265] = {.count = 1, .reusable = true}, REDUCE(sym_exports, 2),
  [267] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
  [269] = {.count = 2, .reusable = true}, REDUCE(sym__qualified_module_identifier, 1), SHIFT(140),
  [272] = {.count = 2, .reusable = true}, REDUCE(sym_qualified_module_identifier, 2), SHIFT(140),
  [275] = {.count = 1, .reusable = true}, SHIFT(9),
  [277] = {.count = 1, .reusable = false}, SHIFT(137),
  [279] = {.count = 1, .reusable = true}, SHIFT(108),
  [281] = {.count = 1, .reusable = true}, REDUCE(sym_module, 3),
  [283] = {.count = 1, .reusable = true}, REDUCE(sym_exports, 5),
  [285] = {.count = 1, .reusable = true}, REDUCE(aux_sym_qualified_module_identifier_repeat1, 2),
  [287] = {.count = 1, .reusable = true}, REDUCE(sym_qualified_variable_operator, 3),
  [289] = {.count = 1, .reusable = true}, REDUCE(sym_exports, 4),
  [291] = {.count = 1, .reusable = true}, REDUCE(sym__top_declarations, 3),
  [293] = {.count = 1, .reusable = true}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_curry_external_scanner_create(void);
void tree_sitter_curry_external_scanner_destroy(void *);
bool tree_sitter_curry_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_curry_external_scanner_serialize(void *, char *);
void tree_sitter_curry_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_curry(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__variable_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_curry_external_scanner_create,
      tree_sitter_curry_external_scanner_destroy,
      tree_sitter_curry_external_scanner_scan,
      tree_sitter_curry_external_scanner_serialize,
      tree_sitter_curry_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
